### ISSUE TITLE
Review Ticket #4

### ISSUE THREAD

**Issue by PranavP04** [PranavP04/Pranav-Data-Structures-Repository-Tri-3#5]
### **Graded By Jay Manjrekar | Final Score: 4.6/5**
- [ ] CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [ ] CB Create Task Coding requirements documented
- [ ] Runtime of Code(with comments) on Replit/Intellij
Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [ ] Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
- [ ] Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
- [ ] Hack#1 Add Phone Number to Sign Up / Authorization screen
- [ ] Hack#2 Add logout to CRUD screen
- [ ] Hack#3 Add login_required to another portion of the project
- [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by JayManjrekar** [comment]
**Total Score 4.6**
GitHub pages document the create task, and appear to have all the requirements. +2
For group accounts and logins, they are attempted on the group website flask portfolio, however do not work properly 
Login working, logout not working +1.6/3
For extra credit, they have it completed +1pt
